.Dd $Mdocdate$
.Dt matelcli 1
.Os OpenBSD 6.9
.Sh NAME
.Nm 0002
.Nd displays prime numbers
.Sh SYNOPSIS
.Nm 0002
.Sh DESCRIPTION
.Nm 0002
prints the sequence of all primes to the terminal.
.Pp
.Nm 0002
is \fInot\fR fully optimised -- there do exist programs which are
superior to
.Nm 0002 .
.Sh AUTHOR
.Nm 0002
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq varikvalefor@aol.com .
