PROGRAM A0002
INTEGER :: A;
A = 1;
DO WHILE(A > 0)
  IF(ISPRIME(A) == 1) THEN
    PRINT *, A;
  END IF
  A = A + 1;
END DO
END PROGRAM A0002

FUNCTION ISPRIME(A) RESULT(K)
INTEGER, INTENT(IN) :: A;
INTEGER :: B, C, K;
B = 1;
THESHIFT: DO C = 2, FLOOR(SQRT(FLOAT(A)))
  IF (MOD(A,C) == 0) THEN
    B = 0;
    EXIT THESHIFT;
  END IF
END DO THESHIFT
K = B;
END FUNCTION
