(DEFUN ISPRIME (K)
	(DEFPARAMETER OKAWEEWEE 0)
	(LOOP FOR I FROM 2 TO (ISQRT K) DO
		(IF (EQUAL 0 (MOD K I))
			(PROGN
				(DEFPARAMETER OKAWEEWEE 1)
				(RETURN))))
	(EQUAL OKAWEEWEE 0)
)

(DEFPARAMETER N 2)
(LOOP WHILE (EQUAL 1 1) DO
	(DEFPARAMETER N (+ 1 N))
	(IF (ISPRIME N) (PRINT N))
)
