.Dd $Mdocdate$
.Dt matelcli 1
.Os OpenBSD 6.9
.Sh NAME
.Nm 0004
.Nd reverses text
.Sh SYNOPSIS
.Nm 0004
.Sh DESCRIPTION
.Nm 0004
reads a line from the standard input, reverses this line, and outputs
the reversed line to the standard output.
.Sh AUTHOR
.Nm 0004
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq varikvalefor@aol.com .
