.Dd $Mdocdate$
.Dt matelcli 1
.Os OpenBSD 6.9
.Sh NAME
.Nm 0003
.Nd outputs list of numbers
.Sh SYNOPSIS
.Nm 0003
.Ar a b
.Sh DESCRIPTION
.Nm 0003
.Ar a b
prints the sequence of all integers
.Va c
such that
.Ar a
<=
.Va c
<=
.Ar b ,
where
.Ar a
and
.Ar b
are nonnegative integers which are written in base 10.
.Sh AUTHOR
.Nm 0003
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq varikvalefor@aol.com .
