.Dd $Mdocdate$
.Dt matelcli 1
.Os OpenBSD 6.9
.Sh NAME
.Nm 0023
.Nd stripped-down version of .Nm ls
.Sh SYNOPSIS
.Nm matelcli
.Op Ar directory
.Sh DESCRIPTION
.Nm 0023
lists the contents of the current directory in no particular order.
.Pp
.Nm 0023
.Ar k
lists the contents of directory
.Ar k
in no particular order.
.Sh AUTHOR
.Nm 0023
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq varikvalefor@aol.com .
