.Dd $Mdocdate$
.Dt matelcli 1
.Os OpenBSD 6.9
.Sh NAME
.Nm 0005
.Nd outputs large number
.Sh SYNOPSIS
.Nm 0005
.Ar a
.Sh DESCRIPTION
.Nm 0005
.Ar a
prints the number which results from concatenating all integers
.Va k
such that
1 <=
.Va k
<=
.Ar a ,
where
.Ar a
is a nonnegative integer.
.Sh AUTHOR
.Nm 0005
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq varikvalefor@aol.com .
